### ISSUE TITLE
data structure

### ISSUE THREAD

**Issue by RedTartan04** [ricklupton/rmscene#1]
Hi, it's so good to see someone tackles the new file format :)
So it seems reMarkable has switched to a distributed data base approach to store and sync notebooks ? An LWW-CRDT
https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type#LWW-Element-Set_(Last-Write-Wins-Element-Set) ? 
I don't know much about these kind of data types but I wonder if it's so generic that there must be a de/serialization library available already?

**Comment by ricklupton** [comment]
I don't think it's using an LWW Element Set (that you linked to) specifically. It seems to use a type of [sequence CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type#Sequence_CRDTs) for the text and scene elements, with plain LWW values for e.g. layer names. I haven't figured out if the sequence CRDT is an existing/named type (I expect it is) or what it's called.

I don't know if there's a library for working with it. It would be useful if there is. But as far as I know the binary format is custom for the .rm file format anyway.

**Comment by ricklupton** [comment]
(closing as I don't know what can be done about it, but suggestions welcome!)
