### ISSUE TITLE
Question regarding coordinates of SceneGlyphItemBlock

### ISSUE THREAD

**Issue by Joogle** [ricklupton/rmscene#11]
I am trying to export pdfs with highlighted text from my remarkable in a way that allows me to have the highlights show up as  annotations in a reference manager i.e. Jabref. I already managed to extract the highlights with rmscene (Thank you very much for your work on this by the way!) But I am struggling to understand how to interpret the coordinates  I get from:
```
with open(
    "result/fe28f8d6-82d7-4ee2-a1df-0c6cbf1a1785/73efd3f4-f6b9-43c8-9507-db728a545848.rm",
    "rb",
) as f:
    result = [
        block for block in read_blocks(f) if isinstance(block, SceneGlyphItemBlock)
    ]

x = result[0].item.value.rectangles[0].x
y = result[0].item.value.rectangles[0].y
w = result[0].item.value.rectangles[0].w
h = result[0].item.value.rectangles[0].h
```
The resulting values I got where the following:
x=-777.0586776928369, 
y=154.8036158772884, 
w=518.3922791561563, 
h=113.49999618530273

And I don't quite get how I can translate that into the coordinates I need for generating the annotations via pdf-annotate.
I would assume that the x and y value represent the coordinate of the top left(?) corner of the highlighted area, while w is representing the width and h the height. What I don't understand is why the x value is negative or how the coordinate system works in the remarkable files. Where is it centered, how do I find out the total size, etc.

Maybe you could give me some pointers?

**Comment by j6k4m8** [comment]
from this, it looks like the origin is the center point of the page

https://github.com/ricklupton/rmc/blob/main/src/rmc/exporters/svg.py#L52

so a negative x value represents the left side of the page... but I'm not totally certain this is right, since the remarkable templates are 1404×1872px and -777 would be off the x=-702 margin... maybe this is excluding the menubar width?

**Comment by Azeirah** [comment]
I can confirm that x=-702 is the top-left of the ReMarkable screen. You can go lower than -702 (and higher than 701) if you expand the page by swiping to the left/right. Though I don't think that's the case for your notebook, @Joogle?

There are still some unknowns about the coordinates. Although I do think @ricklupton knows more about this than I do. For instance, if you have written text to the page with the text tool, all coordinates of everything on the page gets shifted.

I also recall there being a block having x coordinate offsets that might affect the position of other blocks on the page, although I genuinely have no idea how that one works. I also don't see it in the rmc rendering logic. After some searching, it's the `TreeNodeBlock`: https://github.com/ricklupton/rmscene/blob/10e5e4e896c1c5ead47c34998967a3951e06a735/src/rmscene/scene_stream.py#L148

I don't recall the menubar affecting x-coordinates.

**Comment by Joogle** [comment]
So, first of all, thanks for the input everyone!
I finally got around to testing stuff for a bit.
The document I am using is a simple .odt file in A4 format, that I converted to .pdf. 
I tried what @ricklupton suggested and the lines seem to use the same coordinate system as the highlight rectangle.

However the size of the coordinate system seems to be bigger than the standard remarkable one and also seems to have a different center than described.
On the X-Axis I have coordinates from approximately  -990 to 990 while the coordinates on the y axis seem to range from somewhere around 10 to 2630. (I tried to approximate those with dots I made with the ballpoint pen, just in case that's relevant) So I would assume that the center point in the pdf would be in the middle of the top of the page. 
That's not what I expected, but maybe I misunderstood what you were saying.

In any case in order to work with the coordinates it would be very helpful to get the actual dimensions of the page, is there any way to do that?

**Comment by Azeirah** [comment]
The dimensions of the page are calculated based on the minmax positions of all items in the scene. It's not available as a pre-computed number anywhere as far as I have seen.

I think ReMarkable does something to fit the PDF onto the screen.

A4 = 210x297mm = aspect ratio of 70/99

RM = 1404x1872px = aspect ratio of 3/4

The result is 1990x2630px ~ish

So the RM was scaled

1990 / 1404 = 995/702 ≃ 99/70

2630 / 1872 = 131.5/93.6 ≃ 99/70

These values make sense given the aspect ratio of A4.

So to fit a PDF onto the RM, we need to compute

```py
pdf_width = 210
pdf_height = 297
aspect_in = pdf_width / pdf_height
RM_WIDTH = 1404
RM_HEIGHT = 1872

notebook_width = RM_WIDTH / aspect_in
notebook_height = RM_HEIGHT / aspect_in

print(notebook_width, notebook_height) # 1985, 2647
```

This is similar to what you measured.

So the coordinates stored in the annotations are probably not scaled by the inverse aspect ratio (or, I guess the portrait aspect ratio)

**Comment by Joogle** [comment]
I managed to get it working with the approach you described @Azeirah - Thank you! 
The following produces the input PDF with a rectangle around the highlighted text. I didn't yet manage to have the annotation show up in Jabref, but that's a different problem. 
```
pdf_width = 210
pdf_height = 297
aspect_in = pdf_width / pdf_height
RM_WIDTH = 1404
RM_HEIGHT = 1872
notebook_width = RM_WIDTH / aspect_in
notebook_height = RM_HEIGHT / aspect_in


# With x,y,w,h coming from the SceneGlyphItemBlock
x1= x + (notebook_width/2)
y2 = notebook_height - y
x2 = x1+w
y2 = y1-h

from pdf_annotate import PdfAnnotator, Location, Appearance
a = PdfAnnotator("input.pdf")
a.set_page_dimensions((notebook_width, notebook_height), 0)

a.add_annotation(
    "square",
    Location(x1=x1, y1=y1, x2=x2, y2=y2, page=0),
    Appearance(stroke_color=(1, 0, 0), stroke_width=5),
)
a.write("result.pdf")
```
