### ISSUE TITLE
enabling debug dumping-as-json mode for v6 files

### ISSUE THREAD

**Issue by adq** [ricklupton/rmscene#25]
If you set `SCENE_FILE_V6_DEBUG=1` prior to running xochitl will start dumping the rm files as json files for debug when it saves them - it'll output in journalctl what the filenames are.

If you wanna enable this persistently:
```
[Unit]
Description=reMarkable main application
StartLimitIntervalSec=600
StartLimitBurst=4
OnFailure=remarkable-fail.service
After=home.mount
Wants=rm-sync.service

[Service]
ExecStart=/usr/bin/xochitl --system
Restart=on-failure
WatchdogSec=60
Environment="SCENE_FILE_V6_DEBUG=1"

[Install]
WantedBy=multi-user.target
```

**Comment by Azeirah** [comment]
Super interesting! Do you have an example of what such a file looks like? I don't have access to my ReMarkable at the moment since it's bricked :x

**Comment by adq** [comment]
Sorry to hear that! 

I'll get a sample one together soon, but they can be pretty huge. Its the entire file in plain JSON format. For example here's block type 13:

```
    "SceneInfo": {
        "backgroundVisible": {
            "timestamp": "0:0",
            "value": 1
        },
        "currentLayer": {
            "timestamp": "1:1892",
            "value": "0:11"
        },
        "rootDocumentVisible": {
            "timestamp": "1:1887",
            "value": 1
        }
    },
```

and block type 8:
```
        {
            "CrdtTombstoneItem": {
                "deletedLength": 20,
                "id": "1:43",
                "left": "1:42",
                "parentId": "0:11",
                "right": "0:0"
            }
        },
```
 patches incoming :D

**Comment by Azeirah** [comment]
Oh my

Did you discover this debugging flag yourself? It's stupidly useful for what we're doing here 😅😅

**Comment by adq** [comment]
yeah, just found them this afternoon! I'd spotted there were some interesting strings which were clearly about "writing scene files out as JSON" so I went poking about with Ghidra.. and there it was!

**Comment by Azeirah** [comment]
Awesome! You should really share this discovery in the remarkable discord!

**Comment by adq** [comment]
Good plan: done!

Here's a simple sample of the RM file and its matching json file.

[2584527c-7667-4b1c-994c-ae70215653e4.rm.gz](https://github.com/ricklupton/rmscene/files/15140269/2584527c-7667-4b1c-994c-ae70215653e4.rm.gz)
[2584527c-7667-4b1c-994c-ae70215653e4.rm.tmp.json.gz](https://github.com/ricklupton/rmscene/files/15140270/2584527c-7667-4b1c-994c-ae70215653e4.rm.tmp.json.gz)

**Comment by ricklupton** [comment]
@adq that's great! Thanks for sharing and for the patches.

**Comment by ricklupton** [comment]
I've added a link to this issue in the README and so will close it here.

**Comment by JustRedTTG** [comment]
Where are these located?

**Comment by JustRedTTG** [comment]
What version does this support? It doesn't work for me
