### ISSUE TITLE
Release version 0.5.0 to pypy

### ISSUE THREAD

**Issue by Azeirah** [ricklupton/rmscene#26]
I noticed that version 0.4.0 is the latest on PyPi.

Maybe it might be nice to have a Github action to do this automatically when a new version is created?

**Comment by ricklupton** [comment]
I think it's already published and there is a Github action to do this -- https://github.com/ricklupton/rmscene/actions/runs/6423632112 -- is it not working?

**Comment by Azeirah** [comment]
Must have been multiple errors on my end, because I'm looking at pypi and it's definitely released. Not sure what went wrong there
