### ISSUE TITLE
Exported SVG does not contain all the strokes inside viewbox

### ISSUE THREAD

**Issue by iacore** [ricklupton/rmscene#27]
Sometimes, all the graphical elements are offset for some reason. Like this:

![image](https://github.com/ricklupton/rmscene/assets/74560659/63e35979-1ff4-4f11-9f50-1ef9cb919ccf)

or this, if the canvas is landscape:

![image](https://github.com/ricklupton/rmscene/assets/74560659/f6d069f1-2292-4b32-a674-ce9508562634)

I can probably fix this myself. How do I start?

**Comment by ricklupton** [comment]
Is this using https://github.com/ricklupton/rmc ? If so let's move the issue there

**Comment by iacore** [comment]
Yes this is rmc. Also I no longer own a RM11x.

**Comment by ricklupton** [comment]
Might have been fixed by https://github.com/ricklupton/rmc/pull/19
