### ISSUE TITLE
ReMarkable version 3.3 support

### ISSUE THREAD

**Issue by Azeirah** [ricklupton/rmscene#9]
ReMarkable released beta v3.3, introducing bold and italic text for the keyboard.

I made a test notebook with the following contents:

- Bolded text
- Italicized text
- Text in a list

Processing this file results in the following output:

```
File: "bolded text.notebook" (325e6c07-7f7c-4ddb-b75a-2de392a05bf6)

Some data has not been read. The data may have been written using a newer format than this reader supports.
In MainBlockInfo(offset=84, size=7, extra_data=b'', block_type=0, min_version=1, current_version=1) only read 5 bytes
In MainBlockInfo(offset=99, size=25, extra_data=b'', block_type=10, min_version=0, current_version=1) only read 20 bytes
In SubBlockInfo(offset=1014, size=7, extra_data=b'') only read 2 bytes
In SubBlockInfo(offset=1078, size=7, extra_data=b'') only read 2 bytes
In SubBlockInfo(offset=1266, size=7, extra_data=b'') only read 2 bytes
In SubBlockInfo(offset=1382, size=7, extra_data=b'') only read 2 bytes
Unknown block type 8. Skipping 20 bytes.
In SubBlockInfo(offset=10332, size=233, extra_data=b'') only read 229 bytes
In SubBlockInfo(offset=10598, size=135, extra_data=b'') only read 131 bytes
In SubBlockInfo(offset=10766, size=4713, extra_data=b'') only read 4709 bytes
In SubBlockInfo(offset=15512, size=233, extra_data=b'') only read 229 bytes
In SubBlockInfo(offset=15778, size=135, extra_data=b'') only read 131 bytes
In SubBlockInfo(offset=15946, size=4713, extra_data=b'') only read 4709 bytes
In SubBlockInfo(offset=20692, size=233, extra_data=b'') only read 229 bytes
In SubBlockInfo(offset=20958, size=135, extra_data=b'') only read 131 bytes
In SubBlockInfo(offset=21126, size=4713, extra_data=b'') only read 4709 bytes
```

[bolded text.zip](https://github.com/ricklupton/rmscene/files/11104112/bolded.text.zip)

**Comment by Azeirah** [comment]
I do have another exception trace, but I cannot share the source file due to privacy concerns (it is not my file either).

It has similar `SubBlockInfo` messages, but also includes an error message at the end.

```
In SubBlockInfo(offset=130798, size=205, extra_data=b'') only read 201 bytes
In SubBlockInfo(offset=131036, size=345, extra_data=b'') only read 341 bytes
In SubBlockInfo(offset=131414, size=513, extra_data=b'') only read 509 bytes
Unknown block type 8. Skipping 19 bytes.
Unknown block type 8. Skipping 17 bytes.
Unknown block type 8. Skipping 19 bytes.
Unknown block type 8. Skipping 19 bytes.
Unknown block type 8. Skipping 19 bytes.
Traceback (most recent call last):
  File \"\/usr\/local\/lib\/python3.10\/runpy.py\", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"\/usr\/local\/lib\/python3.10\/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"\/app\/remarks\/__main__.py\", line 151, in <module>
    main()
  File \"\/app\/remarks\/__main__.py\", line 147, in main
    run_remarks(input_dir, output_dir, **args_dict)
  File \"\/app\/remarks\/remarks.py\", line 94, in run_remarks
    process_document(metadata_path, out_path, doc_type, **kwargs)
  File \"\/app\/remarks\/remarks.py\", line 189, in process_document
    dimensions = determine_document_dimensions(path)
  File \"\/app\/remarks\/conversion\/parsing.py\", line 180, in determine_document_dimensions
    for el in tree.walk():
  File \"\/app\/.venv\/lib\/python3.10\/site-packages\/rmscene\/scene_tree.py\", line 48, in walk
    yield from _walk_items(self.root)
  File \"\/app\/.venv\/lib\/python3.10\/site-packages\/rmscene\/scene_tree.py\", line 54, in _walk_items
    yield from _walk_items(child)
  File \"\/app\/.venv\/lib\/python3.10\/site-packages\/rmscene\/scene_tree.py\", line 53, in _walk_items
    for child in item.children.values():
  File \"\/app\/.venv\/lib\/python3.10\/site-packages\/rmscene\/crdt_sequence.py\", line 62, in values
    return [self[item_id] for item_id in self]
  File \"\/app\/.venv\/lib\/python3.10\/site-packages\/rmscene\/crdt_sequence.py\", line 62, in <listcomp>
    return [self[item_id] for item_id in self]
  File \"\/app\/.venv\/lib\/python3.10\/site-packages\/rmscene\/crdt_sequence.py\", line 54, in __iter__
    yield from toposort_items(self._items.values())
  File \"\/app\/.venv\/lib\/python3.10\/site-packages\/rmscene\/crdt_sequence.py\", line 127, in toposort_items
    assert next_items
    AssertionError`"}
```

**Comment by ricklupton** [comment]
Thanks for reporting! Will have a look at how this works.

Are you interested in the new features, or is there something specific about the basic lines/text that worked before but doesn't work with the new version?

**Comment by ricklupton** [comment]
> I do have another exception trace, but I cannot share the source file due to privacy concerns (it is not my file either)

I'm not sure what's going on here. Maybe there is a way to strip content from files while preserving the structure so they can be shared more easily.

**Comment by Azeirah** [comment]
> Thanks for reporting! Will have a look at how this works.
> 
> Are you interested in the new features, or is there something specific about the basic lines/text that worked before but doesn't work with the new version?

With time, I hope to see full support for the new features. For the time being, I'm most interested in stability.



> I'm not sure what's going on here. Maybe there is a way to strip content from files while preserving the structure so they can be shared more easily.

I think it's definitely a good idea to look into some form of sanitization. If all text values and point values are either scrambled or stripped entirely then a file should not contain much more than just the structure itself.

**Comment by Azeirah** [comment]
I have the issue occurring in one of my own files. Unfortunately, it's in my "diary" file.

I am willing to share the file if that helps you debug the issue, but I'm for sure not going to post the file here on Github. Is it ok if I mail you about this? Thanks!

**Comment by ricklupton** [comment]
Yes feel free to email

**Comment by Azeirah** [comment]
Just wanted to confirm, did you receive the email? My client warned me about the large (20mb) file attachment, I sent it last week

**Comment by Azeirah** [comment]
I don't entirely understand the code yet, but it looks like this happens when there's a cyclic dependency in the CRDT IDs.

Given what I see, I think it's related to a bug that even the ReMarkable itself shows every now and then. There's a somewhat common bug where some scribbles that should be visible on a notebook dissappear despite having been written.

The linedata itself is actually not gone, but the CRDT sequence doesn't resolve. From what I can see, this issue affects

1. The ReMarkable tablet itself
2. The built-in send-as-email (convert to pdf) feature
3. RMScene

For instance, in the file I sent the last page is missing some characters at the last word at the end of the page. I wrote "opsturen", but the ReMarkable shows "opstu". I think this data does still exist though, in debugging I found these strange values:

![afbeelding](https://github.com/ricklupton/rmscene/assets/4040870/8a0a3088-4311-4005-893e-4ff37e82b98e)

I confirmed my suspicion of this being a bug in the ReMarkable software itself by confirming there's text cut off on pages where the assertion error happens.

There's an assertion error on page index 57 for instance. I opened the page 58 on my ReMarkable and similar to the last page in the notebook, the last word is cut off. I wrote "betalen", but it shows "beta"

For what it's worth, I think it's better not to fail with an assertion, but to raise the Cyclic dependency error as the one below so it can be handled better.

This one is on ReMarkable I'm pretty sure.

**Comment by ricklupton** [comment]
Thanks, I did receive your file but haven’t had time to look at it yet. 

Sounds like you are able to consistently see the issue. I agree if this is due to problems with the input data avoiding the assertion error and logging a warning that some text has been lost would be better. I’m not sure if it’s possible to recover. 

Pull requests welcome if you like!

**Comment by ricklupton** [comment]
@Azeirah sorry for the delay here... I tried the file you sent but none of the pages seem to cause the error, either in the latest version or in a few previous releases. Are you still seeing a problem with this?

**Comment by Azeirah** [comment]
My tablet has been software bricked for a long while now. I received the RMPP yesterday.

I expanded scrybble with a "ask for help" option, where scrybble customers can choose to share their RM documents.

From what I can gather, the biggest "issue" in general is bug or issue reproduction. My intent was to use this data to build up the test suite.

Regarding privacy, see the video:

https://github.com/user-attachments/assets/c0996f20-019c-4d44-b276-032c615d282a

**Comment by Azeirah** [comment]
I'm in general rethinking how software like scrybble can help sustainably grow open-source communities financially and with social capital.

It's part of a business model I'm approaching where community and customers are _always_ central. It's still a work-in-progress, but in general I believe people deserve better. Both open-source maintainers as well as end-users.
